name: flutter_gps_calendar_poc
description: POC Flutter avec GPS et intÃ©gration Google/Microsoft Calendar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # Geolocation
  geolocator: ^12.0.0

  # Google Calendar
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  # Microsoft OAuth2 & Graph API
  http: ^1.2.2
  flutter_web_auth_2: ^4.1.0

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
